# Generated by Django 6.0.3 on 2026-04-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aluno",
            name="data_nascimento",
        ),
        migrations.RemoveField(
            model_name="aluno",
            name="fotografia",
        ),
        migrations.AddField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(default="cursos/default.jpg", upload_to="cursos/"),
        ),
    ]
