# Generated by Django 6.0.3 on 2026-03-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('email_institucional', models.EmailField(blank=True, max_length=254)),
                ('pagina_pessoal', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sigla', models.CharField(blank=True, max_length=3)),
                ('instituicao', models.CharField(default='Universidade Lusófona', max_length=30)),
                ('departamento', models.CharField(blank=True, max_length=5)),
                ('ano_inicio', models.PositiveIntegerField()),
                ('ano_fim_previsto', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True)),
                ('site_oficial', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(help_text='Ex: linguagem, framework, BD, ferramenta, etc.', max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('site_oficial', models.URLField(blank=True)),
                ('nivel_interesse', models.PositiveSmallIntegerField(help_text='Classificação 1-5, por exemplo.')),
                ('destaques', models.TextField(blank=True, help_text='Aspetos mais relevantes (pontos fortes, casos de uso, etc.).')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('resumo', models.TextField()),
                ('conceitos_aplicados', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('video_demo', models.URLField(blank=True)),
                ('repo_github', models.URLField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tecnologias', models.ManyToManyField(related_name='projetos', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=150)),
                ('tipo', models.CharField(help_text='Ex: Licenciatura, Curso curto, Certificação, Workshop.', max_length=80)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('carga_horaria', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('certificado_url', models.URLField(blank=True)),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.tecnologia')),
            ],
            options={
                'ordering': ['data_inicio', 'data_fim'],
            },
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano_letivo', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=150)),
                ('resumo', models.TextField()),
                ('area_tematica', models.CharField(max_length=150)),
                ('classificacao', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nivel_interesse', models.PositiveSmallIntegerField(help_text='Classificação pessoal de interesse (1-5).')),
                ('repo_github', models.URLField(blank=True)),
                ('documento', models.URLField(blank=True)),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tfcs', to='portfolio.docente')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.CharField(help_text='Ex: Iniciante, Intermédio, Avançado.', max_length=50)),
                ('categoria', models.CharField(help_text='Ex: Técnica, Soft Skill, Linguística, etc.', max_length=80)),
                ('projetos_relacionados', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.projeto')),
                ('tecnologias_relacionadas', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.tecnologia')),
                ('tfcs_relacionados', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.tfc')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ano', models.PositiveSmallIntegerField()),
                ('semestre', models.PositiveSmallIntegerField()),
                ('ects', models.DecimalField(decimal_places=1, max_digits=4)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ucs/')),
                ('docentes', models.ManyToManyField(related_name='ucs', to='portfolio.docente')),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ucs', to='portfolio.licenciatura')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='portfolio.unidadecurricular'),
        ),
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidade_tipo', models.CharField(choices=[('LICENCIATURA', 'Licenciatura'), ('UC', 'Unidade Curricular'), ('PROJETO', 'Projeto'), ('TECNOLOGIA', 'Tecnologia'), ('TFC', 'TFC'), ('COMPETENCIA', 'Competência'), ('FORMACAO', 'Formação')], max_length=20)),
                ('entidade_id', models.PositiveIntegerField(help_text='ID da instância da entidade a que este registo se refere.')),
                ('titulo', models.CharField(max_length=200)),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('descricao_processo', models.TextField(help_text='Descrição do processo de desenvolvimento/modelação.')),
                ('decisoes_tomadas', models.TextField(blank=True)),
                ('erros_encontrados', models.TextField(blank=True)),
                ('correcoes', models.TextField(blank=True)),
                ('justificacao_modelacao', models.TextField(blank=True)),
                ('uso_ia', models.TextField(blank=True, help_text='Descrição de como ferramentas de IA foram usadas (ou não).')),
                ('evidencias_papel', models.ImageField(blank=True, help_text='Fotografias de caderno, DER, esquemas, etc.', null=True, upload_to='makingof/')),
                ('relacionado_formacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='making_of', to='portfolio.formacao')),
                ('relacionado_projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='making_of', to='portfolio.projeto')),
                ('relacionado_tecnologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='making_of', to='portfolio.tecnologia')),
                ('relacionado_tfc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='making_of', to='portfolio.tfc')),
                ('relacionado_uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='making_of', to='portfolio.unidadecurricular')),
            ],
        ),
    ]
