# Generated by Django 6.0.3 on 2026-04-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("titulo", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("grau", models.CharField(max_length=50)),
                ("ects_total", models.IntegerField()),
                ("duracao_anos", models.IntegerField()),
                ("area_cientifica", models.CharField(max_length=100)),
                ("url_site", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entidade_relacionada", models.CharField(max_length=50)),
                ("entidade_id", models.IntegerField()),
                ("descricao", models.TextField()),
                ("decisoes", models.TextField()),
                ("erros_correcoes", models.TextField(blank=True)),
                ("foto_papel", models.ImageField(blank=True, upload_to="makingof/")),
                ("data_registo", models.DateField(auto_now_add=True)),
                ("uso_ia", models.TextField(blank=True)),
                ("fase", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("categoria", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("versao", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=50)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("conceitos_uc", models.TextField()),
                ("ano", models.IntegerField()),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                (
                    "formacoes",
                    models.ManyToManyField(blank=True, to="portfolio.formacao"),
                ),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("resumo", models.TextField()),
                ("orientador", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("url_documento", models.URLField(blank=True)),
                ("area_tematica", models.CharField(max_length=100)),
                ("keywords", models.CharField(max_length=300)),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(max_length=20)),
                ("ects", models.IntegerField()),
                ("ano_curricular", models.IntegerField()),
                ("semestre", models.CharField(max_length=10)),
                ("descricao", models.TextField()),
                (
                    "docentes",
                    models.ManyToManyField(related_name="ucs", to="portfolio.docente"),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano_letivo", models.IntegerField()),
                ("semestre", models.CharField(max_length=10)),
                ("nota_media", models.DecimalField(decimal_places=2, max_digits=4)),
                ("nr_alunos", models.IntegerField()),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
