# Generated by Django 6.0.3 on 2026-04-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("hackathon", "Hackathon"),
                            ("conferencia", "Conferência"),
                            ("workshop", "Workshop"),
                            ("webinar", "Webinar"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=200)),
                (
                    "certificado",
                    models.FileField(blank=True, upload_to="eventos/certificados/"),
                ),
                ("imagem", models.ImageField(blank=True, upload_to="eventos/")),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="eventos", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
