# Generated by Django 6.0.3 on 2026-05-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('base_dados', 'Base de Dados'), ('storage', 'Storage'), ('outro', 'Outro')], max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tecnologia',
                'verbose_name_plural': 'Tipos de Tecnologia',
            },
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnologias', to='portfolio.tipotecnologia'),
        ),
    ]
